# Generated by Django 3.0 on 2021-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='purpose',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
